// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/submit-family-interest.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var submit_family_interest_default = defineTool({
  name: "submit_family_interest",
  title: "Submit family interest",
  description: "Add a family to the Tomtebudet interest list. Families are notified when Christmas 2026 bookings open. Requires email and name; location and children info are optional.",
  inputSchema: {
    email: z.string().email().describe("Family contact email (required)."),
    name: z.string().min(1).max(100).describe("Family/contact name (required)."),
    location: z.string().max(100).optional().describe("City or area in Sweden, optional."),
    children_info: z.string().max(500).optional().describe("Optional info about the children (ages, names).")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ email, name, location, children_info }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!supabaseUrl || !supabaseKey) {
      return {
        content: [{ type: "text", text: "Server not configured." }],
        isError: true
      };
    }
    const supabase = createClient(supabaseUrl, supabaseKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { error } = await supabase.from("family_interest").insert({
      email,
      name,
      location: location ?? null,
      children_info: children_info ?? null
    });
    if (error) {
      return {
        content: [{ type: "text", text: `Could not save: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Thanks ${name}! You're on the Tomtebudet interest list. We'll email ${email} when bookings for Christmas 2026 open.`
        }
      ],
      structuredContent: { ok: true, email, name }
    };
  }
});

// src/lib/mcp/tools/get-platform-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var INFO = `Tomtebudet is a Swedish platform for booking verified Santas ("jultomtar") for home visits at Christmas.

Status: Pre-launch. Bookings open for Christmas 2026.
Website: https://tomtebudet.se

What families can do today:
- Join the interest list at https://tomtebudet.se/intresse-familj to be notified when bookings open.

What Santas can do today:
- Apply to become a verified Santa at https://tomtebudet.se/bli-tomte.

Key pages:
- How it works: /sa-funkar-det
- Privacy & security: /integritet-sakerhet
- Terms: /kopvillkor
- Contact: /kontakt`;
var get_platform_info_default = defineTool2({
  name: "get_platform_info",
  title: "Get Tomtebudet info",
  description: "Get an overview of Tomtebudet: what the platform is, current pre-launch status, and how families and Santas can get involved before Christmas 2026 bookings open.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: INFO }] })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tomtebudet-mcp",
  title: "Tomtebudet",
  version: "0.1.0",
  instructions: "Tools for Tomtebudet, a Swedish platform for booking verified Santas. Use `get_platform_info` for an overview of the platform and its current pre-launch status. Use `submit_family_interest` to add a family to the interest list so they are notified when Christmas 2026 bookings open.",
  tools: [get_platform_info_default, submit_family_interest_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
